# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'seminar21' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for seminar21

pod 'CHIPageControl', '~> 0.1.3'

# individual page control
pod 'CHIPageControl', '~> 0.1.3'
pod 'Alamofire', '~> 4.8.2'

  target 'seminar21Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'seminar21UITests' do
    # Pods for testing
  end



end
